### PR TITLE
Update to cosmwasm v1.0

### PR DESCRIPTION
**Pull request by luca992**
I updated all dependencies to the latest and refactored everything for cosmwasm-v1.0.

All the tests are passing.
There was a LOT to refactor. And I'm honestly just getting the hang of rust. So a careful review would probably be best.

Some notes:
* For `append_tx_for_addr` and `get_txs` inside `state.rs`. I'm not positive I correctly ported from secret-toolkit:0.3's `AppendStoreMut` to using  secret-toolkit:0.5's `AppendStore` with suffixes. 
* For my refactoring of `HumanAddress` to `String` and `Addr`. All query and execute messages should now use `String` for addresses and all response messages should be returning addresses as `Addr`. I wasn't positive if response messages should also return `String` addresses? But I ended up going with `Addr` since any address returned should be validated at that point.
* In tests I had to change `block_time` and `time_of_minting` values from `1571797419` to `1571797419879305533`. I'm not sure if that is correct.
* I renamed structs containing `Init` to `Instantiate`. But, that might not be desired everywhere, as it makes names kind of long. I left variables containing `init` as `init` because changing `post_init_callback` to -> `post_instantiate_callback` is long. So let me know what you think as far as naming conventions go. Personally long names are fine with me and I would change everything to `Instantiate` instead of `init`, but I know other people do not agree.

### CODE REVIEW

**Comment by luca992** [comment]
So compile is working, however I just tried uploading the wasm to a testnet and I'm getting the error:

```
{
    "code": 3,
    "message":
        "failed to execute message;
        message index: 0: Execution error: Error during static Wasm validation:
        Contract is not CosmWasm v0.10 or v1. To support v0.10 please fix the former two errors,
        to supports v1 please fix the latter two errors:
        $[
            Err(StaticValidationErr
                {
                    msg: "Wasm contract doesn't have required export: 'cosmwasm_vm_version_3'.
                            Exports required by VM: ['cosmwasm_vm_version_3', 'query', 'init',
                            'handle', 'allocate', 'deallocate'].",
                    backtrace: Backtrace(
                        0: cosmwasm_sgx_vm::errors::vm_error::VmError::static_validation_err
                        1: cosmwasm_sgx_vm::compatability::check_wasm_exports
                        2: cosmwasm_sgx_vm::compatability::check_wasm
                        3: cosmwasm_sgx_vm::cache::CosmCache<S,A,Q>::save_wasm
                        4: go_cosmwasm::do_create
                        5: create\n
                        6: _cgo_0f53c1153487_C2func_create\n
                        7: <unknown>
                    )
                }
            ),
            Err(StaticValidationErr
                {
                    msg: "Wasm contract requires unsupported import:
                            '__wbindgen_placeholder__.__wbindgen_describe'. Imports supported by VM:
                            ['env.db_read', 'env.db_write', 'env.db_remove', 'env.canonicalize_address',
                            'env.humanize_address', 'env.query_chain', 'env.secp256k1_verify',
                            'env.secp256k1_recover_pubkey', 'env.secp256k1_sign', 'env.ed25519_verify',
                            'env.ed25519_batch_verify', 'env.ed25519_sign', 'env.db_scan', 'env.db_next',
                            'env.debug_print'].",
                    backtrace: Backtrace(
                        0: cosmwasm_sgx_vm::errors::vm_error::VmError::static_validation_err
                        1: cosmwasm_sgx_vm::compatability::check_wasm_imports
                        2: cosmwasm_sgx_vm::compatability::check_wasm
                        3: cosmwasm_sgx_vm::cache::CosmCache<S,A,Q>::save_wasm
                        4: go_cosmwasm::do_create
                        5: create
                        6: _cgo_0f53c1153487_C2func_create
                        7: <unknown>\n
                    )
                }
            ),
            Ok(()),
            Err(StaticValidationErr
                {
                msg: "Wasm contract requires unsupported import:
                        '__wbindgen_placeholder__.__wbindgen_describe'. Imports supported by VM:
                        ['env.db_read', 'env.db_write', 'env.db_remove', 'env.addr_validate', 'env.addr_canonicalize',
                        'env.addr_humanize', 'env.secp256k1_verify', 'env.secp256k1_recover_pubkey',
                        'env.secp256k1_sign', 'env.ed25519_verify', 'env.ed25519_batch_verify', 'env.ed25519_sign',
                        'env.debug', 'env.query_chain', 'env.db_scan', 'env.db_next'].",
                backtrace: Backtrace(
                        0: cosmwasm_sgx_vm::errors::vm_error::VmError::static_validation_err
                        1: cosmwasm_sgx_vm::compatability::check_wasm_imports
                        2: cosmwasm_sgx_vm::compatability::check_wasm
                        3: cosmwasm_sgx_vm::cache::CosmCache<S,A,Q>::save_wasm
                        4: go_cosmwasm::do_create
                        5: create
                        6: _cgo_0f53c1153487_C2func_create
                        7: <unknown>
                    )
                }
            )
        ]: create contract failed: invalid request",
    "details": []
}
```

**Comment by luca992** [comment]
fixed it by downgrading rand_chacha, and rand_core

**Comment by baedrik** [comment]
Thanks!  Sorry I wasn't able to get to this sooner.  I merged it into a new branch, and I'll start going through it and if I find anything that needs changed, I'll just handle it myself and merge it to master.  Thanks again!

**Comment by luca992** [comment]
One other thing I think everywhere `TODO remove this when BlockInfo becomes available to queries` is mentioned can be resolved now that block env.block is available in queries. I didn't update that. @baedrik

**Comment by baedrik** [comment]
Yeah, I'll be making that change.  Also, one thing I noticed that you likely want to change on your custom 721 contract is that you should be using block.time.seconds() when checking expiration instead of nanos()

v0.10 721 contracts only have seconds available to them when they check env.block.time, so in order for all usage/parameters to be consistent v1.0 should be using seconds as well.  Otherwise, apps will need to know whether a contract is 0.10 or 1.0 anytime it sets a time based expiration

**Pull request merged**
