### PR TITLE
cargo update following release of secret-toolkit-permit v0.3.1

### PR DESCRIPTION
**Pull request by reuvenpo**
This release decreases the binary size of the SNIP721 module by about 10% !

### CODE REVIEW

**Comment by reuvenpo** [comment]
The CI is failing because of clippy warnings now, so i'll leave that for a future PR

**Comment by baedrik** [comment]
Awesome!  Thank you!

**Comment by baedrik** [comment]
> The CI is failing because of clippy warnings now, so i'll leave that for a future PR

I can clean up the clippy warnings.  Thanks again!

**Comment by reuvenpo** [comment]
You're welcome! 😄

**Pull request merged**
